package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agent generated by hbm2java
 */
@Entity
@Table(name="agent"
    ,catalog="abdev01"
)
public class Agent  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -9114500740559239794L;
	private String agentid;
     private Agentcategory agentcategory;
     private Branch branch;
     private Status status;
     private String accountno;
     private String address;
     private String agentcode;
     private String contactno;
     private String contactperson;
     private Date createdtime;
     private String email;
     private String fax;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private String name;

    public Agent() {
    }

	
    public Agent(String agentid, Status status) {
        this.agentid = agentid;
        this.status = status;
    }
    public Agent(String agentid, Agentcategory agentcategory, Branch branch, Status status, String accountno, String address, String agentcode, String contactno, String contactperson, Date createdtime, String email, String fax, Date lastupdatedtime, String lastupdateduser, String name) {
       this.agentid = agentid;
       this.agentcategory = agentcategory;
       this.branch = branch;
       this.status = status;
       this.accountno = accountno;
       this.address = address;
       this.agentcode = agentcode;
       this.contactno = contactno;
       this.contactperson = contactperson;
       this.createdtime = createdtime;
       this.email = email;
       this.fax = fax;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="AGENTID", unique=true, nullable=false, length=15)
    public String getAgentid() {
        return this.agentid;
    }
    
    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AGENTCATEGORY")
    public Agentcategory getAgentcategory() {
        return this.agentcategory;
    }
    
    public void setAgentcategory(Agentcategory agentcategory) {
        this.agentcategory = agentcategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BRANCH")
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="ACCOUNTNO", length=64)
    public String getAccountno() {
        return this.accountno;
    }
    
    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    
    @Column(name="ADDRESS")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="AGENTCODE", length=16)
    public String getAgentcode() {
        return this.agentcode;
    }
    
    public void setAgentcode(String agentcode) {
        this.agentcode = agentcode;
    }

    
    @Column(name="CONTACTNO", length=16)
    public String getContactno() {
        return this.contactno;
    }
    
    public void setContactno(String contactno) {
        this.contactno = contactno;
    }

    
    @Column(name="CONTACTPERSON", length=64)
    public String getContactperson() {
        return this.contactperson;
    }
    
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="EMAIL")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="FAX", length=16)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="NAME", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


