package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgentuserbatchId generated by hbm2java
 */
@Embeddable
public class AgentuserbatchId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3062903760853631260L;
	private String username;
     private String batchid;

    public AgentuserbatchId() {
    }

    public AgentuserbatchId(String username, String batchid) {
       this.username = username;
       this.batchid = batchid;
    }
   


    @Column(name="USERNAME", unique=true, nullable=false, length=60)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


    @Column(name="BATCHID", unique=true, nullable=false, length=24)
    public String getBatchid() {
        return this.batchid;
    }
    
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AgentuserbatchId) ) return false;
		 AgentuserbatchId castOther = ( AgentuserbatchId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getBatchid()==castOther.getBatchid()) || ( this.getBatchid()!=null && castOther.getBatchid()!=null && this.getBatchid().equals(castOther.getBatchid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getBatchid() == null ? 0 : this.getBatchid().hashCode() );
         return result;
   }   


}


