package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agentuser generated by hbm2java
 */
@Entity
@Table(name="agentuser"
    ,catalog="abdev01"
)
public class Agentuser  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2671827215825655297L;
	private String username;
     private Status status;
     private Userrole userrole;
     private Date createdtime;
     private Boolean firstlogin;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private byte loginflag;
     private String masterkey;
     private String name;
     private String nic;
     private String password;
     private Byte pincount;
     private String sessionkey;
     private String usercode;
     private String hashpassword;
     private String officeid;
     private String currworkdate;
     private Set<Terminallocation> terminallocations = new HashSet<Terminallocation>(0);
     private Set<Agentuserbatch> agentuserbatches = new HashSet<Agentuserbatch>(0);
     private Set<TerminallocationHistory> terminallocationHistories = new HashSet<TerminallocationHistory>(0);

    public Agentuser() {
    }

	
    public Agentuser(String username, Status status, Userrole userrole, byte loginflag, String password) {
        this.username = username;
        this.status = status;
        this.userrole = userrole;
        this.loginflag = loginflag;
        this.password = password;
    }
    public Agentuser(String username, Status status, Userrole userrole, Date createdtime, Boolean firstlogin, Date lastupdatedtime, String lastupdateduser, byte loginflag, String masterkey, String name, String nic, String password, Byte pincount, String sessionkey, String usercode, String hashpassword, String officeid, String currworkdate, Set<Terminallocation> terminallocations, Set<Agentuserbatch> agentuserbatches, Set<TerminallocationHistory> terminallocationHistories) {
       this.username = username;
       this.status = status;
       this.userrole = userrole;
       this.createdtime = createdtime;
       this.firstlogin = firstlogin;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.loginflag = loginflag;
       this.masterkey = masterkey;
       this.name = name;
       this.nic = nic;
       this.password = password;
       this.pincount = pincount;
       this.sessionkey = sessionkey;
       this.usercode = usercode;
       this.hashpassword = hashpassword;
       this.officeid = officeid;
       this.currworkdate = currworkdate;
       this.terminallocations = terminallocations;
       this.agentuserbatches = agentuserbatches;
       this.terminallocationHistories = terminallocationHistories;
    }
   
     @Id 

    
    @Column(name="USERNAME", unique=true, nullable=false, length=60)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLE", nullable=false)
    public Userrole getUserrole() {
        return this.userrole;
    }
    
    public void setUserrole(Userrole userrole) {
        this.userrole = userrole;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="FIRSTLOGIN")
    public Boolean getFirstlogin() {
        return this.firstlogin;
    }
    
    public void setFirstlogin(Boolean firstlogin) {
        this.firstlogin = firstlogin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="LOGINFLAG", nullable=false)
    public byte getLoginflag() {
        return this.loginflag;
    }
    
    public void setLoginflag(byte loginflag) {
        this.loginflag = loginflag;
    }

    
    @Column(name="MASTERKEY")
    public String getMasterkey() {
        return this.masterkey;
    }
    
    public void setMasterkey(String masterkey) {
        this.masterkey = masterkey;
    }

    
    @Column(name="NAME", length=64)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NIC", length=16)
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }

    
    @Column(name="PASSWORD", nullable=false, length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="PINCOUNT")
    public Byte getPincount() {
        return this.pincount;
    }
    
    public void setPincount(Byte pincount) {
        this.pincount = pincount;
    }

    
    @Column(name="SESSIONKEY", length=60)
    public String getSessionkey() {
        return this.sessionkey;
    }
    
    public void setSessionkey(String sessionkey) {
        this.sessionkey = sessionkey;
    }

    
    @Column(name="USERCODE", length=64)
    public String getUsercode() {
        return this.usercode;
    }
    
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    
    @Column(name="HASHPASSWORD", length=50)
    public String getHashpassword() {
        return this.hashpassword;
    }
    
    public void setHashpassword(String hashpassword) {
        this.hashpassword = hashpassword;
    }

    
    @Column(name="OFFICEID", length=45)
    public String getOfficeid() {
        return this.officeid;
    }
    
    public void setOfficeid(String officeid) {
        this.officeid = officeid;
    }

    
    @Column(name="CURRWORKDATE", length=45)
    public String getCurrworkdate() {
        return this.currworkdate;
    }
    
    public void setCurrworkdate(String currworkdate) {
        this.currworkdate = currworkdate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agentuser")
    public Set<Terminallocation> getTerminallocations() {
        return this.terminallocations;
    }
    
    public void setTerminallocations(Set<Terminallocation> terminallocations) {
        this.terminallocations = terminallocations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agentuser")
    public Set<Agentuserbatch> getAgentuserbatches() {
        return this.agentuserbatches;
    }
    
    public void setAgentuserbatches(Set<Agentuserbatch> agentuserbatches) {
        this.agentuserbatches = agentuserbatches;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agentuser")
    public Set<TerminallocationHistory> getTerminallocationHistories() {
        return this.terminallocationHistories;
    }
    
    public void setTerminallocationHistories(Set<TerminallocationHistory> terminallocationHistories) {
        this.terminallocationHistories = terminallocationHistories;
    }




}


