package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Agentuserbatch generated by hbm2java
 */
@Entity
@Table(name="agentuserbatch"
    ,catalog="abdev01"
    , uniqueConstraints = {@UniqueConstraint(columnNames="USERNAME"), @UniqueConstraint(columnNames="BATCHID")} 
)
public class Agentuserbatch  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -7046178791815458225L;
	private AgentuserbatchId id;
     private Agentuser agentuser;
     private Status status;
     private Terminal terminal;
     private Date createdtime;
     private Date lastupdatedtime;
     private String lastupdateduser;

    public Agentuserbatch() {
    }

	
    public Agentuserbatch(AgentuserbatchId id, Agentuser agentuser) {
        this.id = id;
        this.agentuser = agentuser;
    }
    public Agentuserbatch(AgentuserbatchId id, Agentuser agentuser, Status status, Terminal terminal, Date createdtime, Date lastupdatedtime, String lastupdateduser) {
       this.id = id;
       this.agentuser = agentuser;
       this.status = status;
       this.terminal = terminal;
       this.createdtime = createdtime;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="username", column=@Column(name="USERNAME", unique=true, nullable=false, length=60) ), 
        @AttributeOverride(name="batchid", column=@Column(name="BATCHID", unique=true, nullable=false, length=24) ) } )
    public AgentuserbatchId getId() {
        return this.id;
    }
    
    public void setId(AgentuserbatchId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERNAME", unique=true, nullable=false, insertable=false, updatable=false)
    public Agentuser getAgentuser() {
        return this.agentuser;
    }
    
    public void setAgentuser(Agentuser agentuser) {
        this.agentuser = agentuser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TERMINALID")
    public Terminal getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }




}


