package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agentcategory generated by hbm2java
 */
@Entity
@Table(name="agentcategory"
    ,catalog="abdev01"
)
public class Agentcategory  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2096187161186199027L;
	private String categorycode;
     private Status status;
     private Date createdtime;
     private String description;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private String remarks;
     private Set<Agentparam> agentparams = new HashSet<Agentparam>(0);
     private Set<Agent> agents = new HashSet<Agent>(0);

    public Agentcategory() {
    }

	
    public Agentcategory(String categorycode, Status status, String description) {
        this.categorycode = categorycode;
        this.status = status;
        this.description = description;
    }
    public Agentcategory(String categorycode, Status status, Date createdtime, String description, Date lastupdatedtime, String lastupdateduser, String remarks, Set<Agentparam> agentparams, Set<Agent> agents) {
       this.categorycode = categorycode;
       this.status = status;
       this.createdtime = createdtime;
       this.description = description;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.remarks = remarks;
       this.agentparams = agentparams;
       this.agents = agents;
    }
   
     @Id 

    
    @Column(name="CATEGORYCODE", unique=true, nullable=false, length=16)
    public String getCategorycode() {
        return this.categorycode;
    }
    
    public void setCategorycode(String categorycode) {
        this.categorycode = categorycode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="DESCRIPTION", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="REMARKS")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agentcategory")
    public Set<Agentparam> getAgentparams() {
        return this.agentparams;
    }
    
    public void setAgentparams(Set<Agentparam> agentparams) {
        this.agentparams = agentparams;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agentcategory")
    public Set<Agent> getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set<Agent> agents) {
        this.agents = agents;
    }




}


