package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Audittrace generated by hbm2java
 */
@Entity
@Table(name="audittrace"
    ,catalog="abdev01"
)
public class Audittrace  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -3443844319200137990L;
	private Long audittraceid;
     private String affectedkey;
     private Date createdtime;
     private String description;
     private String ip;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private String newvalue;
     private String oldvalue;
     private String pagecode;
     private String remarks;
     private String taskcode;
     private String userrolecode;

    public Audittrace() {
    }

	
    public Audittrace(String description, String userrolecode) {
        this.description = description;
        this.userrolecode = userrolecode;
    }
    public Audittrace(String affectedkey, Date createdtime, String description, String ip, Date lastupdatedtime, String lastupdateduser, String newvalue, String oldvalue, String pagecode, String remarks, String taskcode, String userrolecode) {
       this.affectedkey = affectedkey;
       this.createdtime = createdtime;
       this.description = description;
       this.ip = ip;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.newvalue = newvalue;
       this.oldvalue = oldvalue;
       this.pagecode = pagecode;
       this.remarks = remarks;
       this.taskcode = taskcode;
       this.userrolecode = userrolecode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="AUDITTRACEID", unique=true, nullable=false)
    public Long getAudittraceid() {
        return this.audittraceid;
    }
    
    public void setAudittraceid(Long audittraceid) {
        this.audittraceid = audittraceid;
    }

    
    @Column(name="AFFECTEDKEY", length=128)
    public String getAffectedkey() {
        return this.affectedkey;
    }
    
    public void setAffectedkey(String affectedkey) {
        this.affectedkey = affectedkey;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="DESCRIPTION", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="IP", length=64)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="NEWVALUE")
    public String getNewvalue() {
        return this.newvalue;
    }
    
    public void setNewvalue(String newvalue) {
        this.newvalue = newvalue;
    }

    
    @Column(name="OLDVALUE")
    public String getOldvalue() {
        return this.oldvalue;
    }
    
    public void setOldvalue(String oldvalue) {
        this.oldvalue = oldvalue;
    }

    
    @Column(name="PAGECODE", length=16)
    public String getPagecode() {
        return this.pagecode;
    }
    
    public void setPagecode(String pagecode) {
        this.pagecode = pagecode;
    }

    
    @Column(name="REMARKS")
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="TASKCODE", length=16)
    public String getTaskcode() {
        return this.taskcode;
    }
    
    public void setTaskcode(String taskcode) {
        this.taskcode = taskcode;
    }

    
    @Column(name="USERROLECODE", nullable=false)
    public String getUserrolecode() {
        return this.userrolecode;
    }
    
    public void setUserrolecode(String userrolecode) {
        this.userrolecode = userrolecode;
    }




}


