package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberAttendance generated by hbm2java
 */
@Entity
@Table(name="member_attendance"
    ,catalog="abdev01"
)
public class MemberAttendance  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8208080396656292573L;
	private Long id;
     private String officerid;
     private String clusterid;
     private String groupid;
     private String customerid;
     private String attendance;
     private String terminalid;
     private String batchid;
     private Date createdtime;
     private Date lastupdatedtime;
     private String lastupdateduser;

    public MemberAttendance() {
    }

    public MemberAttendance(String officerid, String clusterid, String groupid, String customerid, String attendance, String terminalid, String batchid, Date createdtime, Date lastupdatedtime, String lastupdateduser) {
       this.officerid = officerid;
       this.clusterid = clusterid;
       this.groupid = groupid;
       this.customerid = customerid;
       this.attendance = attendance;
       this.terminalid = terminalid;
       this.batchid = batchid;
       this.createdtime = createdtime;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="OFFICERID", length=64)
    public String getOfficerid() {
        return this.officerid;
    }
    
    public void setOfficerid(String officerid) {
        this.officerid = officerid;
    }

    
    @Column(name="CLUSTERID", length=8)
    public String getClusterid() {
        return this.clusterid;
    }
    
    public void setClusterid(String clusterid) {
        this.clusterid = clusterid;
    }

    
    @Column(name="GROUPID", length=8)
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    
    @Column(name="CUSTOMERID", length=40)
    public String getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    
    @Column(name="ATTENDANCE", length=2)
    public String getAttendance() {
        return this.attendance;
    }
    
    public void setAttendance(String attendance) {
        this.attendance = attendance;
    }

    
    @Column(name="TERMINALID", length=16)
    public String getTerminalid() {
        return this.terminalid;
    }
    
    public void setTerminalid(String terminalid) {
        this.terminalid = terminalid;
    }

    
    @Column(name="BATCHID", length=16)
    public String getBatchid() {
        return this.batchid;
    }
    
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }




}


