package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name="member"
    ,catalog="abdev01"
)
public class Member  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -3792487808945712823L;
	private Long id;
     private Group group;
     private Status status;
     private String memberdetails;
     private Date createdtime;
     private Date lastupdatedtime;
     private String lastupdateduser;

    public Member() {
    }

	
    public Member(Status status) {
        this.status = status;
    }
    public Member(Group group, Status status, String memberdetails, Date createdtime, Date lastupdatedtime, String lastupdateduser) {
       this.group = group;
       this.status = status;
       this.memberdetails = memberdetails;
       this.createdtime = createdtime;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GROUP")
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="MEMBERDETAILS", length=128)
    public String getMemberdetails() {
        return this.memberdetails;
    }
    
    public void setMemberdetails(String memberdetails) {
        this.memberdetails = memberdetails;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }




}


