package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagesectionuserrole generated by hbm2java
 */
@Entity
@Table(name="pagesectionuserrole"
    ,catalog="abdev01"
)
public class Pagesectionuserrole  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3719253507996433499L;
	private PagesectionuserroleId id;
     private Page page;
     private Section section;
     private Userrole userrole;
     private Date createdtime;
     private Date lastupdatedtime;
     private String lastupdateduser;

    public Pagesectionuserrole() {
    }

	
    public Pagesectionuserrole(PagesectionuserroleId id, Page page, Section section, Userrole userrole) {
        this.id = id;
        this.page = page;
        this.section = section;
        this.userrole = userrole;
    }
    public Pagesectionuserrole(PagesectionuserroleId id, Page page, Section section, Userrole userrole, Date createdtime, Date lastupdatedtime, String lastupdateduser) {
       this.id = id;
       this.page = page;
       this.section = section;
       this.userrole = userrole;
       this.createdtime = createdtime;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="page", column=@Column(name="PAGE", nullable=false, length=16) ), 
        @AttributeOverride(name="section", column=@Column(name="SECTION", nullable=false, length=16) ), 
        @AttributeOverride(name="userrole", column=@Column(name="USERROLE", nullable=false, length=16) ) } )
    public PagesectionuserroleId getId() {
        return this.id;
    }
    
    public void setId(PagesectionuserroleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAGE", nullable=false, insertable=false, updatable=false)
    public Page getPage() {
        return this.page;
    }
    
    public void setPage(Page page) {
        this.page = page;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECTION", nullable=false, insertable=false, updatable=false)
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLE", nullable=false, insertable=false, updatable=false)
    public Userrole getUserrole() {
        return this.userrole;
    }
    
    public void setUserrole(Userrole userrole) {
        this.userrole = userrole;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }




}


