package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagesectionuserroleId generated by hbm2java
 */
@Embeddable
public class PagesectionuserroleId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 5031958528692587737L;
	private String page;
     private String section;
     private String userrole;

    public PagesectionuserroleId() {
    }

    public PagesectionuserroleId(String page, String section, String userrole) {
       this.page = page;
       this.section = section;
       this.userrole = userrole;
    }
   


    @Column(name="PAGE", nullable=false, length=16)
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }


    @Column(name="SECTION", nullable=false, length=16)
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }


    @Column(name="USERROLE", nullable=false, length=16)
    public String getUserrole() {
        return this.userrole;
    }
    
    public void setUserrole(String userrole) {
        this.userrole = userrole;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PagesectionuserroleId) ) return false;
		 PagesectionuserroleId castOther = ( PagesectionuserroleId ) other; 
         
		 return ( (this.getPage()==castOther.getPage()) || ( this.getPage()!=null && castOther.getPage()!=null && this.getPage().equals(castOther.getPage()) ) )
 && ( (this.getSection()==castOther.getSection()) || ( this.getSection()!=null && castOther.getSection()!=null && this.getSection().equals(castOther.getSection()) ) )
 && ( (this.getUserrole()==castOther.getUserrole()) || ( this.getUserrole()!=null && castOther.getUserrole()!=null && this.getUserrole().equals(castOther.getUserrole()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPage() == null ? 0 : this.getPage().hashCode() );
         result = 37 * result + ( getSection() == null ? 0 : this.getSection().hashCode() );
         result = 37 * result + ( getUserrole() == null ? 0 : this.getUserrole().hashCode() );
         return result;
   }   


}


