package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Passwordparm generated by hbm2java
 */
@Entity
@Table(name="passwordparm"
    ,catalog="abdev01"
)
public class Passwordparm  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1010158541055064819L;
	private String paramcode;
     private Date createdtime;
     private String description;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private String value;

    public Passwordparm() {
    }

	
    public Passwordparm(String paramcode) {
        this.paramcode = paramcode;
    }
    public Passwordparm(String paramcode, Date createdtime, String description, Date lastupdatedtime, String lastupdateduser, String value) {
       this.paramcode = paramcode;
       this.createdtime = createdtime;
       this.description = description;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="PARAMCODE", unique=true, nullable=false, length=16)
    public String getParamcode() {
        return this.paramcode;
    }
    
    public void setParamcode(String paramcode) {
        this.paramcode = paramcode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="VALUE", length=100)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


