package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Statuscategory generated by hbm2java
 */
@Entity
@Table(name="statuscategory"
    ,catalog="abdev01"
)
public class Statuscategory  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1218169460653845015L;
	private String statuscategorycode;
     private Date createdtime;
     private String description;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private Set<Status> statuses = new HashSet<Status>(0);

    public Statuscategory() {
    }

	
    public Statuscategory(String statuscategorycode) {
        this.statuscategorycode = statuscategorycode;
    }
    public Statuscategory(String statuscategorycode, Date createdtime, String description, Date lastupdatedtime, String lastupdateduser, Set<Status> statuses) {
       this.statuscategorycode = statuscategorycode;
       this.createdtime = createdtime;
       this.description = description;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.statuses = statuses;
    }
   
     @Id 

    
    @Column(name="STATUSCATEGORYCODE", unique=true, nullable=false, length=16)
    public String getStatuscategorycode() {
        return this.statuscategorycode;
    }
    
    public void setStatuscategorycode(String statuscategorycode) {
        this.statuscategorycode = statuscategorycode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="statuscategory")
    public Set<Status> getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set<Status> statuses) {
        this.statuses = statuses;
    }




}


