package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Terminallocation generated by hbm2java
 */
@Entity
@Table(name="terminallocation"
    ,catalog="abdev01"
    , uniqueConstraints = @UniqueConstraint(columnNames="TERMINALID") 
)
public class Terminallocation  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -428632556157618057L;
	private TerminallocationId id;
     private Agentuser agentuser;
     private Terminal terminal;
     private Date createdtime;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private String latitude;
     private String longitude;

    public Terminallocation() {
    }

	
    public Terminallocation(TerminallocationId id, Agentuser agentuser, Terminal terminal, String latitude, String longitude) {
        this.id = id;
        this.agentuser = agentuser;
        this.terminal = terminal;
        this.latitude = latitude;
        this.longitude = longitude;
    }
    public Terminallocation(TerminallocationId id, Agentuser agentuser, Terminal terminal, Date createdtime, Date lastupdatedtime, String lastupdateduser, String latitude, String longitude) {
       this.id = id;
       this.agentuser = agentuser;
       this.terminal = terminal;
       this.createdtime = createdtime;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.latitude = latitude;
       this.longitude = longitude;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="agentuser", column=@Column(name="AGENTUSER", nullable=false, length=60) ), 
        @AttributeOverride(name="terminalid", column=@Column(name="TERMINALID", unique=true, nullable=false, length=16) ) } )
    public TerminallocationId getId() {
        return this.id;
    }
    
    public void setId(TerminallocationId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AGENTUSER", nullable=false, insertable=false, updatable=false)
    public Agentuser getAgentuser() {
        return this.agentuser;
    }
    
    public void setAgentuser(Agentuser agentuser) {
        this.agentuser = agentuser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TERMINALID", unique=true, nullable=false, insertable=false, updatable=false)
    public Terminal getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="LATITUDE", nullable=false, length=32)
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="LONGITUDE", nullable=false, length=32)
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }




}


