package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Terminal generated by hbm2java
 */
@Entity
@Table(name="terminal"
    ,catalog="abdev01"
    , uniqueConstraints = @UniqueConstraint(columnNames="IMEI") 
)
public class Terminal  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 8082134782197308528L;
	private String terminalid;
     private Branch branch;
     private Status status;
     private Terminalmodel terminalmodel;
     private Terminalversion terminalversion;
     private String assetid;
     private Date createdtime;
     private String description;
     private String imei;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private byte loginflag;
     private String masterkey;
     private Long passcode;
     private String serialno;
     private String sessionkey;
     private String agentid;
     private Set<Agentuserbatch> agentuserbatches = new HashSet<Agentuserbatch>(0);
     private Set<TerminallocationHistory> terminallocationHistories = new HashSet<TerminallocationHistory>(0);
     private Set<Terminallocation> terminallocations = new HashSet<Terminallocation>(0);

    public Terminal() {
    }

	
    public Terminal(String terminalid, Status status, String imei, byte loginflag) {
        this.terminalid = terminalid;
        this.status = status;
        this.imei = imei;
        this.loginflag = loginflag;
    }
    public Terminal(String terminalid, Branch branch, Status status, Terminalmodel terminalmodel, Terminalversion terminalversion, String assetid, Date createdtime, String description, String imei, Date lastupdatedtime, String lastupdateduser, byte loginflag, String masterkey, Long passcode, String serialno, String sessionkey, String agentid, Set<Agentuserbatch> agentuserbatches, Set<TerminallocationHistory> terminallocationHistories, Set<Terminallocation> terminallocations) {
       this.terminalid = terminalid;
       this.branch = branch;
       this.status = status;
       this.terminalmodel = terminalmodel;
       this.terminalversion = terminalversion;
       this.assetid = assetid;
       this.createdtime = createdtime;
       this.description = description;
       this.imei = imei;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.loginflag = loginflag;
       this.masterkey = masterkey;
       this.passcode = passcode;
       this.serialno = serialno;
       this.sessionkey = sessionkey;
       this.agentid = agentid;
       this.agentuserbatches = agentuserbatches;
       this.terminallocationHistories = terminallocationHistories;
       this.terminallocations = terminallocations;
    }
   
     @Id 

    
    @Column(name="TERMINALID", unique=true, nullable=false, length=16)
    public String getTerminalid() {
        return this.terminalid;
    }
    
    public void setTerminalid(String terminalid) {
        this.terminalid = terminalid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BRANCH")
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MODELNO")
    public Terminalmodel getTerminalmodel() {
        return this.terminalmodel;
    }
    
    public void setTerminalmodel(Terminalmodel terminalmodel) {
        this.terminalmodel = terminalmodel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SOFTWAREVERION")
    public Terminalversion getTerminalversion() {
        return this.terminalversion;
    }
    
    public void setTerminalversion(Terminalversion terminalversion) {
        this.terminalversion = terminalversion;
    }

    
    @Column(name="ASSETID", length=16)
    public String getAssetid() {
        return this.assetid;
    }
    
    public void setAssetid(String assetid) {
        this.assetid = assetid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="IMEI", unique=true, nullable=false, length=16)
    public String getImei() {
        return this.imei;
    }
    
    public void setImei(String imei) {
        this.imei = imei;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="LOGINFLAG", nullable=false)
    public byte getLoginflag() {
        return this.loginflag;
    }
    
    public void setLoginflag(byte loginflag) {
        this.loginflag = loginflag;
    }

    
    @Column(name="MASTERKEY", length=60)
    public String getMasterkey() {
        return this.masterkey;
    }
    
    public void setMasterkey(String masterkey) {
        this.masterkey = masterkey;
    }

    
    @Column(name="PASSCODE")
    public Long getPasscode() {
        return this.passcode;
    }
    
    public void setPasscode(Long passcode) {
        this.passcode = passcode;
    }

    
    @Column(name="SERIALNO", length=64)
    public String getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(String serialno) {
        this.serialno = serialno;
    }

    
    @Column(name="SESSIONKEY", length=60)
    public String getSessionkey() {
        return this.sessionkey;
    }
    
    public void setSessionkey(String sessionkey) {
        this.sessionkey = sessionkey;
    }

    
    @Column(name="agentid", length=45)
    public String getAgentid() {
        return this.agentid;
    }
    
    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="terminal")
    public Set<Agentuserbatch> getAgentuserbatches() {
        return this.agentuserbatches;
    }
    
    public void setAgentuserbatches(Set<Agentuserbatch> agentuserbatches) {
        this.agentuserbatches = agentuserbatches;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="terminal")
    public Set<TerminallocationHistory> getTerminallocationHistories() {
        return this.terminallocationHistories;
    }
    
    public void setTerminallocationHistories(Set<TerminallocationHistory> terminallocationHistories) {
        this.terminallocationHistories = terminallocationHistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="terminal")
    public Set<Terminallocation> getTerminallocations() {
        return this.terminallocations;
    }
    
    public void setTerminallocations(Set<Terminallocation> terminallocations) {
        this.terminallocations = terminallocations;
    }




}


