package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Terminaluserprofile generated by hbm2java
 */
@Entity
@Table(name="terminaluserprofile"
    ,catalog="abdev01"
)
public class Terminaluserprofile  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2915870036455668604L;
	private TerminaluserprofileId id;
     private Transactiontype transactiontype;
     private Userrole userrole;
     private Date createdtime;
     private Date lastupdatedtime;
     private String lastupdateduser;

    public Terminaluserprofile() {
    }

	
    public Terminaluserprofile(TerminaluserprofileId id, Transactiontype transactiontype, Userrole userrole) {
        this.id = id;
        this.transactiontype = transactiontype;
        this.userrole = userrole;
    }
    public Terminaluserprofile(TerminaluserprofileId id, Transactiontype transactiontype, Userrole userrole, Date createdtime, Date lastupdatedtime, String lastupdateduser) {
       this.id = id;
       this.transactiontype = transactiontype;
       this.userrole = userrole;
       this.createdtime = createdtime;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="transactiontype", column=@Column(name="TRANSACTIONTYPE", nullable=false, length=16) ), 
        @AttributeOverride(name="userrole", column=@Column(name="USERROLE", nullable=false, length=16) ) } )
    public TerminaluserprofileId getId() {
        return this.id;
    }
    
    public void setId(TerminaluserprofileId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TRANSACTIONTYPE", nullable=false, insertable=false, updatable=false)
    public Transactiontype getTransactiontype() {
        return this.transactiontype;
    }
    
    public void setTransactiontype(Transactiontype transactiontype) {
        this.transactiontype = transactiontype;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLE", nullable=false, insertable=false, updatable=false)
    public Userrole getUserrole() {
        return this.userrole;
    }
    
    public void setUserrole(Userrole userrole) {
        this.userrole = userrole;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }




}


