package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TerminallocationId generated by hbm2java
 */
@Embeddable
public class TerminallocationId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1818867728995055038L;
	private String agentuser;
     private String terminalid;

    public TerminallocationId() {
    }

    public TerminallocationId(String agentuser, String terminalid) {
       this.agentuser = agentuser;
       this.terminalid = terminalid;
    }
   


    @Column(name="AGENTUSER", nullable=false, length=60)
    public String getAgentuser() {
        return this.agentuser;
    }
    
    public void setAgentuser(String agentuser) {
        this.agentuser = agentuser;
    }


    @Column(name="TERMINALID", unique=true, nullable=false, length=16)
    public String getTerminalid() {
        return this.terminalid;
    }
    
    public void setTerminalid(String terminalid) {
        this.terminalid = terminalid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TerminallocationId) ) return false;
		 TerminallocationId castOther = ( TerminallocationId ) other; 
         
		 return ( (this.getAgentuser()==castOther.getAgentuser()) || ( this.getAgentuser()!=null && castOther.getAgentuser()!=null && this.getAgentuser().equals(castOther.getAgentuser()) ) )
 && ( (this.getTerminalid()==castOther.getTerminalid()) || ( this.getTerminalid()!=null && castOther.getTerminalid()!=null && this.getTerminalid().equals(castOther.getTerminalid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAgentuser() == null ? 0 : this.getAgentuser().hashCode() );
         result = 37 * result + ( getTerminalid() == null ? 0 : this.getTerminalid().hashCode() );
         return result;
   }   


}


