package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Terminalparam generated by hbm2java
 */
@Entity
@Table(name="terminalparam"
    ,catalog="abdev01"
)
public class Terminalparam  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2515406685162697566L;
	private String terminalparamcode;
     private Unit unit;
     private Short amount;
     private Date createtime;
     private String description;
     private Date lastupdatedtime;
     private String lastupdateduser;

    public Terminalparam() {
    }

	
    public Terminalparam(String terminalparamcode) {
        this.terminalparamcode = terminalparamcode;
    }
    public Terminalparam(String terminalparamcode, Unit unit, Short amount, Date createtime, String description, Date lastupdatedtime, String lastupdateduser) {
       this.terminalparamcode = terminalparamcode;
       this.unit = unit;
       this.amount = amount;
       this.createtime = createtime;
       this.description = description;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
    }
   
     @Id 

    
    @Column(name="TERMINALPARAMCODE", unique=true, nullable=false, length=32)
    public String getTerminalparamcode() {
        return this.terminalparamcode;
    }
    
    public void setTerminalparamcode(String terminalparamcode) {
        this.terminalparamcode = terminalparamcode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNIT")
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }

    
    @Column(name="AMOUNT")
    public Short getAmount() {
        return this.amount;
    }
    
    public void setAmount(Short amount) {
        this.amount = amount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATETIME", length=19)
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    
    @Column(name="DESCRIPTION", length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }




}


