package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tmpauthrec generated by hbm2java
 */
@Entity
@Table(name="tmpauthrec"
    ,catalog="abdev01"
)
public class Tmpauthrec  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 7875647313027507977L;
	private Integer id;
     private Page page;
     private Status status;
     private Task task;
     private Date createdtime;
     private String key1;
     private String key10;
     private String key11;
     private String key12;
     private String key13;
     private String key14;
     private String key15;
     private String key2;
     private String key3;
     private String key4;
     private String key5;
     private String key6;
     private String key7;
     private String key8;
     private String key9;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private String tmprecord;

    public Tmpauthrec() {
    }

	
    public Tmpauthrec(Page page, Status status, Task task) {
        this.page = page;
        this.status = status;
        this.task = task;
    }
    public Tmpauthrec(Page page, Status status, Task task, Date createdtime, String key1, String key10, String key11, String key12, String key13, String key14, String key15, String key2, String key3, String key4, String key5, String key6, String key7, String key8, String key9, Date lastupdatedtime, String lastupdateduser, String tmprecord) {
       this.page = page;
       this.status = status;
       this.task = task;
       this.createdtime = createdtime;
       this.key1 = key1;
       this.key10 = key10;
       this.key11 = key11;
       this.key12 = key12;
       this.key13 = key13;
       this.key14 = key14;
       this.key15 = key15;
       this.key2 = key2;
       this.key3 = key3;
       this.key4 = key4;
       this.key5 = key5;
       this.key6 = key6;
       this.key7 = key7;
       this.key8 = key8;
       this.key9 = key9;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.tmprecord = tmprecord;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PAGE", nullable=false)
    public Page getPage() {
        return this.page;
    }
    
    public void setPage(Page page) {
        this.page = page;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TASK", nullable=false)
    public Task getTask() {
        return this.task;
    }
    
    public void setTask(Task task) {
        this.task = task;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="KEY1", length=64)
    public String getKey1() {
        return this.key1;
    }
    
    public void setKey1(String key1) {
        this.key1 = key1;
    }

    
    @Column(name="KEY10", length=64)
    public String getKey10() {
        return this.key10;
    }
    
    public void setKey10(String key10) {
        this.key10 = key10;
    }

    
    @Column(name="KEY11", length=64)
    public String getKey11() {
        return this.key11;
    }
    
    public void setKey11(String key11) {
        this.key11 = key11;
    }

    
    @Column(name="KEY12", length=64)
    public String getKey12() {
        return this.key12;
    }
    
    public void setKey12(String key12) {
        this.key12 = key12;
    }

    
    @Column(name="KEY13", length=64)
    public String getKey13() {
        return this.key13;
    }
    
    public void setKey13(String key13) {
        this.key13 = key13;
    }

    
    @Column(name="KEY14", length=64)
    public String getKey14() {
        return this.key14;
    }
    
    public void setKey14(String key14) {
        this.key14 = key14;
    }

    
    @Column(name="KEY15", length=64)
    public String getKey15() {
        return this.key15;
    }
    
    public void setKey15(String key15) {
        this.key15 = key15;
    }

    
    @Column(name="KEY2", length=64)
    public String getKey2() {
        return this.key2;
    }
    
    public void setKey2(String key2) {
        this.key2 = key2;
    }

    
    @Column(name="KEY3", length=64)
    public String getKey3() {
        return this.key3;
    }
    
    public void setKey3(String key3) {
        this.key3 = key3;
    }

    
    @Column(name="KEY4", length=64)
    public String getKey4() {
        return this.key4;
    }
    
    public void setKey4(String key4) {
        this.key4 = key4;
    }

    
    @Column(name="KEY5", length=64)
    public String getKey5() {
        return this.key5;
    }
    
    public void setKey5(String key5) {
        this.key5 = key5;
    }

    
    @Column(name="KEY6", length=64)
    public String getKey6() {
        return this.key6;
    }
    
    public void setKey6(String key6) {
        this.key6 = key6;
    }

    
    @Column(name="KEY7", length=64)
    public String getKey7() {
        return this.key7;
    }
    
    public void setKey7(String key7) {
        this.key7 = key7;
    }

    
    @Column(name="KEY8", length=64)
    public String getKey8() {
        return this.key8;
    }
    
    public void setKey8(String key8) {
        this.key8 = key8;
    }

    
    @Column(name="KEY9", length=64)
    public String getKey9() {
        return this.key9;
    }
    
    public void setKey9(String key9) {
        this.key9 = key9;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="TMPRECORD")
    public String getTmprecord() {
        return this.tmprecord;
    }
    
    public void setTmprecord(String tmprecord) {
        this.tmprecord = tmprecord;
    }




}


