package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactionhistory generated by hbm2java
 */
@Entity
@Table(name="transactionhistory"
    ,catalog="abdev01"
)
public class Transactionhistory  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1669416600230833059L;
	private Long transactionhistoryid;
     private Status status;
     private Date createdtime;
     private Date lastupdatedtime;
     private String transactionid;

    public Transactionhistory() {
    }

	
    public Transactionhistory(Status status, String transactionid) {
        this.status = status;
        this.transactionid = transactionid;
    }
    public Transactionhistory(Status status, Date createdtime, Date lastupdatedtime, String transactionid) {
       this.status = status;
       this.createdtime = createdtime;
       this.lastupdatedtime = lastupdatedtime;
       this.transactionid = transactionid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TRANSACTIONHISTORYID", unique=true, nullable=false)
    public Long getTransactionhistoryid() {
        return this.transactionhistoryid;
    }
    
    public void setTransactionhistoryid(Long transactionhistoryid) {
        this.transactionhistoryid = transactionhistoryid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="TRANSACTIONID", nullable=false, length=32)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }




}


