package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactiontype generated by hbm2java
 */
@Entity
@Table(name="transactiontype"
    ,catalog="abdev01"
)
public class Transactiontype  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2300026759486849588L;
	private String transactiontypecode;
     private Status status;
     private Date createdtime;
     private String description;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private Set<Terminaluserprofile> terminaluserprofiles = new HashSet<Terminaluserprofile>(0);
     private Set<Agentparam> agentparams = new HashSet<Agentparam>(0);

    public Transactiontype() {
    }

	
    public Transactiontype(String transactiontypecode, Status status) {
        this.transactiontypecode = transactiontypecode;
        this.status = status;
    }
    public Transactiontype(String transactiontypecode, Status status, Date createdtime, String description, Date lastupdatedtime, String lastupdateduser, Set<Terminaluserprofile> terminaluserprofiles, Set<Agentparam> agentparams) {
       this.transactiontypecode = transactiontypecode;
       this.status = status;
       this.createdtime = createdtime;
       this.description = description;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.terminaluserprofiles = terminaluserprofiles;
       this.agentparams = agentparams;
    }
   
     @Id 

    
    @Column(name="TRANSACTIONTYPECODE", unique=true, nullable=false, length=16)
    public String getTransactiontypecode() {
        return this.transactiontypecode;
    }
    
    public void setTransactiontypecode(String transactiontypecode) {
        this.transactiontypecode = transactiontypecode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactiontype")
    public Set<Terminaluserprofile> getTerminaluserprofiles() {
        return this.terminaluserprofiles;
    }
    
    public void setTerminaluserprofiles(Set<Terminaluserprofile> terminaluserprofiles) {
        this.terminaluserprofiles = terminaluserprofiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="transactiontype")
    public Set<Agentparam> getAgentparams() {
        return this.agentparams;
    }
    
    public void setAgentparams(Set<Agentparam> agentparams) {
        this.agentparams = agentparams;
    }




}


