package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name="transactions"
    ,catalog="abdev01"
)
public class Transactions  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 7098662951714021544L;
	private String transactionid;
     private Status status;
     private String accountnumber;
     private String accounttype;
     private String agentid;
     private long amount;
     private String branch;
     private String centerid;
     private Date createdtime;
     private String imageStatus;
     private String invoicenumber;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private String memberid;
     private String responcecode;
     private String terminalid;
     private String rrn;
     private String terminaluser;
     private String tracenumber;
     private String transactiontypecode;
     private String txnDatetimeMb;
     private String txnDatetimeSw;
     private String batchid;
     private String officeid;
     private String clusterid;
     private String groupid;
     private String customerid;
     private String loanid;
     private String receiptNo;

    public Transactions() {
    }

	
    public Transactions(String transactionid, Date createdtime) {
        this.transactionid = transactionid;
        this.createdtime = createdtime;
    }
    public Transactions(String transactionid, Status status, String accountnumber, String accounttype, String agentid, long amount, String branch, String centerid, Date createdtime, String imageStatus, String invoicenumber, Date lastupdatedtime, String lastupdateduser, String memberid, String responcecode, String terminalid, String rrn, String terminaluser, String tracenumber, String transactiontypecode, String txnDatetimeMb, String txnDatetimeSw, String batchid, String officeid, String clusterid, String groupid, String customerid, String loanid, String receiptNo) {
       this.transactionid = transactionid;
       this.status = status;
       this.accountnumber = accountnumber;
       this.accounttype = accounttype;
       this.agentid = agentid;
       this.amount = amount;
       this.branch = branch;
       this.centerid = centerid;
       this.createdtime = createdtime;
       this.imageStatus = imageStatus;
       this.invoicenumber = invoicenumber;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.memberid = memberid;
       this.responcecode = responcecode;
       this.terminalid = terminalid;
       this.rrn = rrn;
       this.terminaluser = terminaluser;
       this.tracenumber = tracenumber;
       this.transactiontypecode = transactiontypecode;
       this.txnDatetimeMb = txnDatetimeMb;
       this.txnDatetimeSw = txnDatetimeSw;
       this.batchid = batchid;
       this.officeid = officeid;
       this.clusterid = clusterid;
       this.groupid = groupid;
       this.customerid = customerid;
       this.loanid = loanid;
       this.receiptNo = receiptNo;
    }
   
     @Id 

    
    @Column(name="TRANSACTIONID", unique=true, nullable=false, length=32)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    
    @Column(name="ACCOUNTNUMBER", length=20)
    public String getAccountnumber() {
        return this.accountnumber;
    }
    
    public void setAccountnumber(String accountnumber) {
        this.accountnumber = accountnumber;
    }

    
    @Column(name="ACCOUNTTYPE", length=40)
    public String getAccounttype() {
        return this.accounttype;
    }
    
    public void setAccounttype(String accounttype) {
        this.accounttype = accounttype;
    }

    
    @Column(name="AGENTID", length=64)
    public String getAgentid() {
        return this.agentid;
    }
    
    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    
    @Column(name="AMOUNT", precision=22)
    public long getAmount() {
        return this.amount;
    }
    
    public void setAmount(long amount) {
        this.amount = amount;
    }

    
    @Column(name="BRANCH", length=16)
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }

    
    @Column(name="CENTERID", length=3)
    public String getCenterid() {
        return this.centerid;
    }
    
    public void setCenterid(String centerid) {
        this.centerid = centerid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="IMAGE_STATUS", length=32)
    public String getImageStatus() {
        return this.imageStatus;
    }
    
    public void setImageStatus(String imageStatus) {
        this.imageStatus = imageStatus;
    }

    
    @Column(name="INVOICENUMBER", length=6)
    public String getInvoicenumber() {
        return this.invoicenumber;
    }
    
    public void setInvoicenumber(String invoicenumber) {
        this.invoicenumber = invoicenumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="MEMBERID", length=40)
    public String getMemberid() {
        return this.memberid;
    }
    
    public void setMemberid(String memberid) {
        this.memberid = memberid;
    }

    
    @Column(name="RESPONCECODE", length=10)
    public String getResponcecode() {
        return this.responcecode;
    }
    
    public void setResponcecode(String responcecode) {
        this.responcecode = responcecode;
    }

    
    @Column(name="TERMINALID", length=16)
    public String getTerminalid() {
        return this.terminalid;
    }
    
    public void setTerminalid(String terminalid) {
        this.terminalid = terminalid;
    }

    
    @Column(name="RRN", length=64)
    public String getRrn() {
        return this.rrn;
    }
    
    public void setRrn(String rrn) {
        this.rrn = rrn;
    }

    
    @Column(name="TERMINALUSER", length=20)
    public String getTerminaluser() {
        return this.terminaluser;
    }
    
    public void setTerminaluser(String terminaluser) {
        this.terminaluser = terminaluser;
    }

    
    @Column(name="TRACENUMBER", length=6)
    public String getTracenumber() {
        return this.tracenumber;
    }
    
    public void setTracenumber(String tracenumber) {
        this.tracenumber = tracenumber;
    }

    
    @Column(name="TRANSACTIONTYPECODE", length=16)
    public String getTransactiontypecode() {
        return this.transactiontypecode;
    }
    
    public void setTransactiontypecode(String transactiontypecode) {
        this.transactiontypecode = transactiontypecode;
    }

    
    @Column(name="TXN_DATETIME_MB", length=14)
    public String getTxnDatetimeMb() {
        return this.txnDatetimeMb;
    }
    
    public void setTxnDatetimeMb(String txnDatetimeMb) {
        this.txnDatetimeMb = txnDatetimeMb;
    }

    
    @Column(name="TXN_DATETIME_SW", length=40)
    public String getTxnDatetimeSw() {
        return this.txnDatetimeSw;
    }
    
    public void setTxnDatetimeSw(String txnDatetimeSw) {
        this.txnDatetimeSw = txnDatetimeSw;
    }

    
    @Column(name="BATCHID", length=45)
    public String getBatchid() {
        return this.batchid;
    }
    
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }

    
    @Column(name="OFFICEID", length=45)
    public String getOfficeid() {
        return this.officeid;
    }
    
    public void setOfficeid(String officeid) {
        this.officeid = officeid;
    }

    
    @Column(name="CLUSTERID", length=45)
    public String getClusterid() {
        return this.clusterid;
    }
    
    public void setClusterid(String clusterid) {
        this.clusterid = clusterid;
    }

    
    @Column(name="GROUPID", length=45)
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    
    @Column(name="CUSTOMERID", length=45)
    public String getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    
    @Column(name="LOANID", length=45)
    public String getLoanid() {
        return this.loanid;
    }
    
    public void setLoanid(String loanid) {
        this.loanid = loanid;
    }

    
    @Column(name="RECEIPT_NO", length=40)
    public String getReceiptNo() {
        return this.receiptNo;
    }
    
    public void setReceiptNo(String receiptNo) {
        this.receiptNo = receiptNo;
    }




}


