package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Unitcategory generated by hbm2java
 */
@Entity
@Table(name="unitcategory"
    ,catalog="abdev01"
)
public class Unitcategory  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2367011062995696225L;
	private String unitcategorycode;
     private Date createdtime;
     private String description;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private String status;
     private Set<Unit> units = new HashSet<Unit>(0);

    public Unitcategory() {
    }

	
    public Unitcategory(String unitcategorycode, String status) {
        this.unitcategorycode = unitcategorycode;
        this.status = status;
    }
    public Unitcategory(String unitcategorycode, Date createdtime, String description, Date lastupdatedtime, String lastupdateduser, String status, Set<Unit> units) {
       this.unitcategorycode = unitcategorycode;
       this.createdtime = createdtime;
       this.description = description;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.status = status;
       this.units = units;
    }
   
     @Id 

    
    @Column(name="UNITCATEGORYCODE", unique=true, nullable=false, length=64)
    public String getUnitcategorycode() {
        return this.unitcategorycode;
    }
    
    public void setUnitcategorycode(String unitcategorycode) {
        this.unitcategorycode = unitcategorycode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="DESCRIPTION", length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="STATUS", nullable=false, length=64)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unitcategory")
    public Set<Unit> getUnits() {
        return this.units;
    }
    
    public void setUnits(Set<Unit> units) {
        this.units = units;
    }




}


