package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name="unit"
    ,catalog="abdev01"
)
public class Unit  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6142803166952399348L;
	private String unitcode;
     private Status status;
     private Unitcategory unitcategory;
     private Date createdtime;
     private String description;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private Set<Terminalparam> terminalparams = new HashSet<Terminalparam>(0);

    public Unit() {
    }

	
    public Unit(String unitcode, Status status) {
        this.unitcode = unitcode;
        this.status = status;
    }
    public Unit(String unitcode, Status status, Unitcategory unitcategory, Date createdtime, String description, Date lastupdatedtime, String lastupdateduser, Set<Terminalparam> terminalparams) {
       this.unitcode = unitcode;
       this.status = status;
       this.unitcategory = unitcategory;
       this.createdtime = createdtime;
       this.description = description;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.terminalparams = terminalparams;
    }
   
     @Id 

    
    @Column(name="UNITCODE", unique=true, nullable=false, length=64)
    public String getUnitcode() {
        return this.unitcode;
    }
    
    public void setUnitcode(String unitcode) {
        this.unitcode = unitcode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UNITCATEGORY")
    public Unitcategory getUnitcategory() {
        return this.unitcategory;
    }
    
    public void setUnitcategory(Unitcategory unitcategory) {
        this.unitcategory = unitcategory;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="DESCRIPTION", length=128)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unit")
    public Set<Terminalparam> getTerminalparams() {
        return this.terminalparams;
    }
    
    public void setTerminalparams(Set<Terminalparam> terminalparams) {
        this.terminalparams = terminalparams;
    }




}


