package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersbranchId generated by hbm2java
 */
@Embeddable
public class UsersbranchId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2795363339412675793L;
	private String branch;
     private String username;

    public UsersbranchId() {
    }

    public UsersbranchId(String branch, String username) {
       this.branch = branch;
       this.username = username;
    }
   


    @Column(name="BRANCH", nullable=false, length=16)
    public String getBranch() {
        return this.branch;
    }
    
    public void setBranch(String branch) {
        this.branch = branch;
    }


    @Column(name="USERNAME", nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersbranchId) ) return false;
		 UsersbranchId castOther = ( UsersbranchId ) other; 
         
		 return ( (this.getBranch()==castOther.getBranch()) || ( this.getBranch()!=null && castOther.getBranch()!=null && this.getBranch().equals(castOther.getBranch()) ) )
 && ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBranch() == null ? 0 : this.getBranch().hashCode() );
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         return result;
   }   


}


