package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userrole generated by hbm2java
 */
@Entity
@Table(name="userrole"
    ,catalog="abdev01"
)
public class Userrole  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -86454342760078562L;
	private String userrolecode;
     private Status status;
     private Userroletype userroletype;
     private Date createdtime;
     private String description;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private Set<Pagesectionuserrole> pagesectionuserroles = new HashSet<Pagesectionuserrole>(0);
     private Set<Users> userses = new HashSet<Users>(0);
     private Set<Agentuser> agentusers = new HashSet<Agentuser>(0);
     private Set<Terminaluserprofile> terminaluserprofiles = new HashSet<Terminaluserprofile>(0);
     private Set<Pagetaskuserrole> pagetaskuserroles = new HashSet<Pagetaskuserrole>(0);

    public Userrole() {
    }

	
    public Userrole(String userrolecode, Date createdtime, Date lastupdatedtime) {
        this.userrolecode = userrolecode;
        this.createdtime = createdtime;
        this.lastupdatedtime = lastupdatedtime;
    }
    public Userrole(String userrolecode, Status status, Userroletype userroletype, Date createdtime, String description, Date lastupdatedtime, String lastupdateduser, Set<Pagesectionuserrole> pagesectionuserroles, Set<Users> userses, Set<Agentuser> agentusers, Set<Terminaluserprofile> terminaluserprofiles, Set<Pagetaskuserrole> pagetaskuserroles) {
       this.userrolecode = userrolecode;
       this.status = status;
       this.userroletype = userroletype;
       this.createdtime = createdtime;
       this.description = description;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.pagesectionuserroles = pagesectionuserroles;
       this.userses = userses;
       this.agentusers = agentusers;
       this.terminaluserprofiles = terminaluserprofiles;
       this.pagetaskuserroles = pagetaskuserroles;
    }
   
     @Id 

    
    @Column(name="USERROLECODE", unique=true, nullable=false, length=16)
    public String getUserrolecode() {
        return this.userrolecode;
    }
    
    public void setUserrolecode(String userrolecode) {
        this.userrolecode = userrolecode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATUS")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USERROLETYPECODE")
    public Userroletype getUserroletype() {
        return this.userroletype;
    }
    
    public void setUserroletype(Userroletype userroletype) {
        this.userroletype = userroletype;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", nullable=false, length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="DESCRIPTION", length=64)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", nullable=false, length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userrole")
    public Set<Pagesectionuserrole> getPagesectionuserroles() {
        return this.pagesectionuserroles;
    }
    
    public void setPagesectionuserroles(Set<Pagesectionuserrole> pagesectionuserroles) {
        this.pagesectionuserroles = pagesectionuserroles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userrole")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userrole")
    public Set<Agentuser> getAgentusers() {
        return this.agentusers;
    }
    
    public void setAgentusers(Set<Agentuser> agentusers) {
        this.agentusers = agentusers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userrole")
    public Set<Terminaluserprofile> getTerminaluserprofiles() {
        return this.terminaluserprofiles;
    }
    
    public void setTerminaluserprofiles(Set<Terminaluserprofile> terminaluserprofiles) {
        this.terminaluserprofiles = terminaluserprofiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userrole")
    public Set<Pagetaskuserrole> getPagetaskuserroles() {
        return this.pagetaskuserroles;
    }
    
    public void setPagetaskuserroles(Set<Pagetaskuserrole> pagetaskuserroles) {
        this.pagetaskuserroles = pagetaskuserroles;
    }




}


