package com.epic.agentbanking.model;
// Generated May 3, 2019 4:22:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="abdev01"
)
public class Users  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -592302928651671762L;
	private String username;
     private Status statusByPasswordstatus;
     private Status statusByStatus;
     private Userrole userrole;
     private Byte attempts;
     private Date createdtime;
     private String employeeid;
     private Date expirydate;
     private String fullname;
     private Date lastloggeddate;
     private Date lastupdatedtime;
     private String lastupdateduser;
     private String password;
     private Set<Usersbranch> usersbranches = new HashSet<Usersbranch>(0);

    public Users() {
    }

	
    public Users(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public Users(String username, Status statusByPasswordstatus, Status statusByStatus, Userrole userrole, Byte attempts, Date createdtime, String employeeid, Date expirydate, String fullname, Date lastloggeddate, Date lastupdatedtime, String lastupdateduser, String password, Set<Usersbranch> usersbranches) {
       this.username = username;
       this.statusByPasswordstatus = statusByPasswordstatus;
       this.statusByStatus = statusByStatus;
       this.userrole = userrole;
       this.attempts = attempts;
       this.createdtime = createdtime;
       this.employeeid = employeeid;
       this.expirydate = expirydate;
       this.fullname = fullname;
       this.lastloggeddate = lastloggeddate;
       this.lastupdatedtime = lastupdatedtime;
       this.lastupdateduser = lastupdateduser;
       this.password = password;
       this.usersbranches = usersbranches;
    }
   
     @Id 

    
    @Column(name="USERNAME", unique=true, nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="PASSWORDSTATUS")
    public Status getStatusByPasswordstatus() {
        return this.statusByPasswordstatus;
    }
    
    public void setStatusByPasswordstatus(Status statusByPasswordstatus) {
        this.statusByPasswordstatus = statusByPasswordstatus;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="STATUS")
    public Status getStatusByStatus() {
        return this.statusByStatus;
    }
    
    public void setStatusByStatus(Status statusByStatus) {
        this.statusByStatus = statusByStatus;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="USERROLE")
    public Userrole getUserrole() {
        return this.userrole;
    }
    
    public void setUserrole(Userrole userrole) {
        this.userrole = userrole;
    }

    
    @Column(name="ATTEMPTS")
    public Byte getAttempts() {
        return this.attempts;
    }
    
    public void setAttempts(Byte attempts) {
        this.attempts = attempts;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDTIME", length=19)
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    
    @Column(name="EMPLOYEEID", length=16)
    public String getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(String employeeid) {
        this.employeeid = employeeid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXPIRYDATE", length=19)
    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    
    @Column(name="FULLNAME", length=100)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTLOGGEDDATE", length=19)
    public Date getLastloggeddate() {
        return this.lastloggeddate;
    }
    
    public void setLastloggeddate(Date lastloggeddate) {
        this.lastloggeddate = lastloggeddate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTUPDATEDTIME", length=19)
    public Date getLastupdatedtime() {
        return this.lastupdatedtime;
    }
    
    public void setLastupdatedtime(Date lastupdatedtime) {
        this.lastupdatedtime = lastupdatedtime;
    }

    
    @Column(name="LASTUPDATEDUSER", length=64)
    public String getLastupdateduser() {
        return this.lastupdateduser;
    }
    
    public void setLastupdateduser(String lastupdateduser) {
        this.lastupdateduser = lastupdateduser;
    }

    
    @Column(name="PASSWORD", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="users")
    public Set<Usersbranch> getUsersbranches() {
        return this.usersbranches;
    }
    
    public void setUsersbranches(Set<Usersbranch> usersbranches) {
        this.usersbranches = usersbranches;
    }




}


